#### **Tensors: The Core of PyTorch**

- Import modules

In [1]:
import torch
import numpy as np
import pandas as pd

**Creating Tensors:**

- Python `list` to PyTorch `tensor`:

In [6]:
# From python list
x = [7, 2, 0, 4]
x_tensor = torch.tensor(x)
print(f"Tensor from Python list: {x_tensor}")
print(f"Tensor data type: {x_tensor.dtype}")

Tensor from Python list: tensor([7, 2, 0, 4])
Tensor data type: torch.int64


- NumPy `array` to PyTorch `tensor`:

In [ ]:
# Converts NumPy array into PyTorch Tensor
# torch.from_numpy()
numpy_arr = np.array([5, 9, 1, 7])
numpy_to_tensor = torch.from_numpy(numpy_arr)
print(f"Tensor from Numpy array: {numpy_to_tensor}")
print(f"Tensor data type: {numpy_to_tensor.dtype}")

Tensor from Numpy array: tensor([5, 9, 1, 7])
Tensor data type: torch.int64


- Pandas `DataFrame` -> NumPy `array` to PyTorch `tensor` 

In [9]:
# Read the data from the csv file into a DataFrame
df = pd.read_csv(r"D:\WorkSpace\Machine Learning\PyTorch-for-Deep-Learning\C1-PyTorch Fundamentals\Module1\LAB3\data.csv")

# Extract the data as a NumPy array from the DataFrame
numpy_array_df = df.values

# Convert DataFrame's value to a PyTorch tensor
df_to_tensor = torch.from_numpy(numpy_array_df)
print(f"Shape of the tensor: {df_to_tensor.shape}")
print(f"Tensor datatype: {df_to_tensor.dtype}")

Shape of the tensor: torch.Size([3, 2])
Tensor datatype: torch.float64


- `torch.zeros()`

In [12]:
zeros = torch.zeros(3, 2)
print(f"Tensor with zeros: \n\n{zeros}")

Tensor with zeros: 

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


- `torch.ones()`

In [14]:
ones = torch.ones(2,3)
print(f"Tensor with ones: \n\n{ones}")

Tensor with ones: 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


- `torch.rand()`

In [17]:
random = torch.rand(2, 3)
print(f"Random tensor: \n\n{random}")

Random tensor: 

tensor([[0.9134, 0.1658, 0.3880],
        [0.7923, 0.6687, 0.6310]])


- `torch.randint(low, high, size())`

In [33]:
random_integer = torch.randint(9, 17, size=(3, 2))
print(f"Random integer: \n\n{random_integer}")

Random integer: 

tensor([[11, 16],
        [14, 16],
        [ 9, 10]])


- `torch.zeros_like()`, `torch.ones_like()`

In [20]:
zeros_like = torch.zeros_like(random)
ones_like = torch.ones_like(random)

print(f"Zeros like tensor: \n\n{zeros_like}\n")
print(f"Ones like tensor: \n\n{ones_like}")

Zeros like tensor: 

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones like tensor: 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


- `torch.arange()`

In [22]:
range_tensor = torch.arange(0, 10, step=1)
print(f"Range tensor: {range_tensor}")

Range tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


- Scaler, Vector, Matrix, Tensor

In [27]:
s = torch.tensor(10)
v = torch.tensor([7, 2, 9, 0])
M = torch.rand(2,3)
T = torch.rand(2, 3, 3)
print(f"Scaler: {s}")
print(f"="*50)
print(f"Vector: {v}")
print(f"="*50)
print(f"MATRIX: \n\n{M}")
print(f"="*50)
print(f"TENSOR: \n\n{T}")

Scaler: 10
Vector: tensor([7, 2, 9, 0])
MATRIX: 

tensor([[0.7529, 0.1189, 0.7403],
        [0.3049, 0.9010, 0.8888]])
TENSOR: 

tensor([[[0.3359, 0.2888, 0.4201],
         [0.9250, 0.0819, 0.3881],
         [0.4701, 0.9422, 0.5361]],

        [[1.0000, 0.1701, 0.3209],
         [0.9031, 0.4952, 0.9806],
         [0.9708, 0.5334, 0.3553]]])


-------

- `tensor.argmax()`, `tensor.max()`



* **dim=0** → across rows (down columns)
* **dim=1** → across columns (across a row)
* **dim=2** → across **depth / channels** (the 3rd axis)

---

**Rule:**
`dim = axis number` in a multi-dim tensor.

Example shape `(N, C, H, W)`:

* dim=0 → batch
* dim=1 → channels
* dim=2 → height
* dim=3 → width


In [61]:
v = torch.randint(5, 17, size=(5,))
print(f"Tensor shape: {v.shape}")
s, _ = v.max(dim=0)
print(f"Tensor v: {v}")
print(f"Maximum value: {s}")

Tensor shape: torch.Size([5])
Tensor v: tensor([12,  7, 16, 11, 12])
Maximum value: 16


In [60]:
V = torch.tensor([[10, 17, 11],
                  [19, 6, 21],
                  [12, 29, 10]])
print(f"Tensor shape: {v.shape}")
m, _ = V.max(dim=0) # Finds max across each column
print(f"Tensor v: \n{V}")
print(f"Maximum across each column: {m}")

Tensor shape: torch.Size([3, 3])
Tensor v: 
tensor([[10, 17, 11],
        [19,  6, 21],
        [12, 29, 10]])
Maximum across each column: tensor([19, 29, 21])


In [59]:
V = torch.tensor([[10, 17, 11],
                  [19, 6, 21],
                  [12, 29, 10]])
print(f"Tensor shape: {v.shape}")
m, _ = V.max(dim=1) # Finds max across each row
print(f"Tensor v: \n{V}")
print(f"Maximum across each row: {m}")

Tensor shape: torch.Size([3, 3])
Tensor v: 
tensor([[10, 17, 11],
        [19,  6, 21],
        [12, 29, 10]])
Maximum across each row: tensor([17, 21, 29])


In [65]:
torch.manual_seed(42)
X = torch.randint(0, 99, size=(3, 2, 2))
max_val, _ = X.max(dim=2)
print(X)
print(max_val)

tensor([[[ 6, 95],
         [97, 58]],

        [[90, 65],
         [25, 77]],

        [[85,  2],
         [67, 76]]])
tensor([[95, 97],
        [90, 77],
        [85, 76]])


**Reshaping & Manipulating:**

- `tensor.shape`, `tensor.ndim`, `tensor.dtype`

- `torch.Tensor.reshape()`

- `torch.Tensor.unsqueeze()`

- `torch.Tensor.squeeze()`

- `torch.Tensor.transpose()`

- `torch.Tensor.flatten()`

- `torch.Tensor.permute()`

- `torch.Tensor.cat()`

- `torch.Tensor.item()`

In [25]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"x tensor shape: {x.shape}")
print(f"x tensor dimension: {x.ndim}")
print(f"x tensor dimension: {x.dtype}")
print(f"Type of the object: {type(x)}")

x tensor shape: torch.Size([2, 3])
x tensor dimension: 2
x tensor dimension: torch.int64
Type of the object: <class 'torch.Tensor'>


- `torch.Tensor.unsqueeze()`

In [66]:
# Add extra dimension
TENSOR = torch.randint(0, 99, size=(2,3))
EXPANDED = TENSOR.unsqueeze(0)
print(f"Shape before adding dimension: {TENSOR.shape}")
print(f"Shape after adding dimension : {EXPANDED.shape}")

Shape before adding dimension: torch.Size([2, 3])
Shape after adding dimension : torch.Size([1, 2, 3])


- `torch.Tensor.squeeze()`

In [67]:
# Removing extra dimension
SQUEEZED = EXPANDED.squeeze()
print(f"Shape before removing dimension: {EXPANDED.shape}")
print(f"Shape after removing dimension : {SQUEEZED.shape}")

Shape before removing dimension: torch.Size([1, 2, 3])
Shape after removing dimension : torch.Size([2, 3])


- `torch.Tensor.reshape()`

In [69]:
T = torch.rand(3, 4)
T_RESHAPED = T.reshape(-1,12)
T_RESHAPED2 = T.reshape(3, 2, 2)
print(f"Shape of T_RESHAPED: {T_RESHAPED.shape}")
print(f"Shape of T_RESHAPED2: {T_RESHAPED2.shape}")

Shape of T_RESHAPED: torch.Size([1, 12])
Shape of T_RESHAPED2: torch.Size([3, 2, 2])


- `torch.Tensor.transpose()`

In [5]:
M = torch.rand(3, 4)
print(f"Shape of M: {M.shape}")
print(f"TENSOR M: \n\n{M}")
print("="*50)
M_TRANSPOSED = M.transpose(0, 1)
print(f"Shape of M_TRANSPOSED: {M_TRANSPOSED.shape}")
print(f"TENSOR M_TRANSPOSED: \n\n{M_TRANSPOSED}")

Shape of M: torch.Size([3, 4])
TENSOR M: 

tensor([[0.1289, 0.7877, 0.1268, 0.4465],
        [0.6276, 0.8884, 0.0596, 0.1334],
        [0.5140, 0.0773, 0.5645, 0.8628]])
Shape of M_TRANSPOSED: torch.Size([4, 3])
TENSOR M_TRANSPOSED: 

tensor([[0.1289, 0.6276, 0.5140],
        [0.7877, 0.8884, 0.0773],
        [0.1268, 0.0596, 0.5645],
        [0.4465, 0.1334, 0.8628]])


In [10]:
M = torch.rand(3, 2, 2)
print(f"Shape of M: {M.shape}")
# print(f"TENSOR M: \n\n{M}")
print("="*50)
M_TRANSPOSED = M.transpose(0, 2)
print(f"Shape of M_TRANSPOSED: {M_TRANSPOSED.shape}")
# print(f"TENSOR M_TRANSPOSED: \n\n{M_TRANSPOSED}")

Shape of M: torch.Size([3, 2, 2])
Shape of M_TRANSPOSED: torch.Size([2, 2, 3])


In [9]:
M = torch.rand(3, 2, 3, 2)
print(f"Shape of M: {M.shape}")
# print(f"TENSOR M: \n\n{M}")
print("="*50)
M_TRANSPOSED = M.transpose(1, 2)
print(f"Shape of M_TRANSPOSED: {M_TRANSPOSED.shape}")
# print(f"TENSOR M_TRANSPOSED: \n\n{M_TRANSPOSED}")

Shape of M: torch.Size([3, 2, 3, 2])
Shape of M_TRANSPOSED: torch.Size([3, 3, 2, 2])


- `torch.flatten()`

In [12]:
X = torch.randn(3, 2, 2, 2)
X_flatten = X.flatten()
print(f"After flattening: {X_flatten.shape}")

After flattening: torch.Size([24])


- `torch.cat()`

In [13]:
# Create two tensors to concatenate
tensor_a = torch.tensor([[1, 2],
                         [3, 4]])
tensor_b = torch.tensor([[5, 6],
                         [7, 8]])

concatenated_tensors = torch.cat((tensor_a, tensor_b), dim=1)
print(f"Concatenated tensor: \n\n{concatenated_tensors}")

Concatenated tensor: 

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


- `.item()` converts tensor datatype to python datatype:

In [ ]:
#
TENSOR = torch.tensor([5, 6, 8, 1, 0])
scalar = TENSOR[3]
print(f"TENSOR value: {scalar}")
print(f"TENSOR value type: {type(scalar)}")
scalar_item = scalar.item()
print(f"Scalar item : {scalar_item}")
print(f"Scalar item type: {type(scalar_item)}")

TENSOR value: 1
TENSOR value type: <class 'torch.Tensor'>
Scalar item : 1
Scalar item type: <class 'int'>


----

**Indexing and Slicing**

In [ ]:
# Access single value from a array
torch.manual_seed(42)
A = torch.randint(1, 99, size=(7,))

# Indexing: A[idx]
print(f"Tensor A: {A}")
print(f"5th Element: {A[5]}")

# Slicing: A[start:end]
# All: A[:]

print(f"All: {A[:]}")

print(f"4th to 5th: {A[3:6]}")

print(f"Last element: {A[-1]}")


Tensor A: tensor([79, 66, 61, 13, 47, 18, 69])
5th Element: 18
All: tensor([79, 66, 61, 13, 47, 18, 69])
3rd to 5th: tensor([13, 47, 18])
Last element: 69


In [25]:
# 0th -> # [[1, 2, 3, 4],
# 1st -> # [5, 6, 7, 8],
# 2nd -> # [9, 10, 11, 12]]

# in 2D Slicing: x[row, column]

x = torch.randint(0, 99, size=(3, 4))
print(f"Tensor x: \n{x}\n")
print(f"2nd row: \n{x[2]}")
print(f"2nd column: \n{x[:,1:2]}")
print(f"Sub part: \n{x[:2, 2:]}")


Tensor x: 
tensor([[86, 76, 24, 54],
        [19, 43, 48, 33],
        [18,  6, 81, 14]])

2nd row: 
tensor([18,  6, 81, 14])
2nd column: 
tensor([[76],
        [43],
        [ 6]])
Sub part: 
tensor([[24, 54],
        [48, 33]])


In [2]:
# Boolean masking
import torch
x = torch.randint(0, 99, size=(3, 4))
mask = x > 6
mask_applied = x[mask]
print(f"Tensor x: \n{x}")
print(f"Masked tensor: \n{mask}")
print(f"Value after applying mask: {mask_applied}")

Tensor x: 
tensor([[33,  2, 38, 70],
        [14, 87, 75, 48],
        [91, 63, 86, 78]])
Masked tensor: 
tensor([[ True, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
Value after applying mask: tensor([33, 38, 70, 14, 87, 75, 48, 91, 63, 86, 78])


----

**Mathematical and Logical Operations:**

In [4]:
# Eelement wise (+ , - , *, /)

tensor_a = torch.randint(0, 99, size=(3,4))
tensor_b = torch.randint(0, 99, size=(3,4))

print(f"TENSOR A + TENSOR B: \n{tensor_a + tensor_b}")
print("=" * 60)
print(f"TENSOR A - TENSOR B: \n{tensor_a - tensor_b}")
print("=" * 60)
print(f"TENSOR A * TENSOR B: \n{tensor_a * tensor_b}")
print("=" * 60)
print(f"TENSOR A / TENSOR B: \n{tensor_a / tensor_b}")

TENSOR A + TENSOR B: 
tensor([[ 81,  55,  96, 149],
        [ 60, 115,  60,  43],
        [ 96, 111, 111, 126]])
TENSOR A - TENSOR B: 
tensor([[-33,  -5,  68,   3],
        [-26,  65, -46,   1],
        [-24,  47, -65,  46]])
TENSOR A * TENSOR B: 
tensor([[1368,  750, 1148, 5548],
        [ 731, 2250,  371,  462],
        [2160, 2528, 2024, 3440]])
TENSOR A / TENSOR B: 
tensor([[0.4211, 0.8333, 5.8571, 1.0411],
        [0.3953, 3.6000, 0.1321, 1.0476],
        [0.6000, 2.4688, 0.2614, 2.1500]])


* **Broadcasting**: The automatic expansion of smaller tensors to match the shape of larger tensors during arithmetic operations.

In [21]:
TENSOR_A = torch.randint(0, 99, size=(3, 4))
TENSOR_B = torch.randint(0, 99, size=(4,))
# print(f"TENSOR A * TENSOR B: \n{TENSOR_A * TENSOR_B}")
print(f"TENSOR A + TENSOR B: \n{TENSOR_A + TENSOR_B}")

TENSOR A + TENSOR B: 
tensor([[134, 135, 144, 145],
        [ 63, 115, 152, 115],
        [ 76, 171,  59, 111]])


In [26]:
# Comparison operators: Element-wise comparisons(>, ==, <)
temperatures = torch.tensor([20, 35, 19, 35, 42])
print("TEMPERATURES: ", temperatures)
print("=" * 50)

is_hot = temperatures > 0
is_cool = temperatures <= 0
is_35_degrees = temperatures == 35
print("\nHOT (> 30 DEGREES):", is_hot)
print("\nHOT (> 30 DEGREES):", temperatures[is_hot])
print("=" * 50)
print("COOL (<= 20 DEGREES):", is_cool)
print("COOL (<= 20 DEGREES):", temperatures[is_cool])
print("=" * 50)
print("EXACTLY 35 DEGREES:", is_35_degrees)
print("EXACTLY 35 DEGREES:", temperatures[is_35_degrees])

TEMPERATURES:  tensor([20, 35, 19, 35, 42])

HOT (> 30 DEGREES): tensor([True, True, True, True, True])

HOT (> 30 DEGREES): tensor([20, 35, 19, 35, 42])
COOL (<= 20 DEGREES): tensor([False, False, False, False, False])
COOL (<= 20 DEGREES): tensor([], dtype=torch.int64)
EXACTLY 35 DEGREES: tensor([False,  True, False,  True, False])
EXACTLY 35 DEGREES: tensor([35, 35])


In [2]:
is_morning = torch.tensor([True, False, False, True])
is_raining = torch.tensor([False, False, True, True])
print("IS MORNING:", is_morning)
print("IS RAINING:", is_raining)
print("-" * 50)

### Logical Operators (&, |)

# Use '&' (AND) to find when it's both morning and raining
morning_and_raining = (is_morning & is_raining)

# Use '|' (OR) to find when it's either morning or raining
morning_or_raining = is_morning | is_raining

print("\nMORNING & (AND) RAINING:", morning_and_raining)
print("MORNING | (OR) RAINING:", morning_or_raining)

IS MORNING: tensor([ True, False, False,  True])
IS RAINING: tensor([False, False,  True,  True])
--------------------------------------------------

MORNING & (AND) RAINING: tensor([False, False, False,  True])
MORNING | (OR) RAINING: tensor([ True, False,  True,  True])


In [7]:
# Mean and Standard Deviation
TENSOR_T = torch.randn(10, 4)
# dim = 0 across column
print(f"Mean of TENSOR_T:\n\n {TENSOR_T.mean(dim=0)}")
print("=" * 50)
# dim = 1 across row

print(f"Standard Deviation of TENSOR_T:\n\n {TENSOR_T.std(dim=1)}")

Mean of TENSOR_T:

 tensor([-0.0412,  0.1114,  0.1704, -0.6341])
Standard Deviation of TENSOR_T:

 tensor([0.6150, 1.5210, 1.6264, 0.8423, 0.9702, 0.7013, 1.2652, 0.8758, 0.9314,
        0.7845])
