#### **Tensors: The Core of PyTorch**

- Import modules

In [1]:
import torch
import numpy as np
import pandas as pd

**Creating Tensors:**

- Python `list` to PyTorch `tensor`:

In [6]:
# From python list
x = [7, 2, 0, 4]
x_tensor = torch.tensor(x)
print(f"Tensor from Python list: {x_tensor}")
print(f"Tensor data type: {x_tensor.dtype}")

Tensor from Python list: tensor([7, 2, 0, 4])
Tensor data type: torch.int64


- NumPy `array` to PyTorch `tensor`:

In [ ]:
# Converts NumPy array into PyTorch Tensor
# torch.from_numpy()
numpy_arr = np.array([5, 9, 1, 7])
numpy_to_tensor = torch.from_numpy(numpy_arr)
print(f"Tensor from Numpy array: {numpy_to_tensor}")
print(f"Tensor data type: {numpy_to_tensor.dtype}")

Tensor from Numpy array: tensor([5, 9, 1, 7])
Tensor data type: torch.int64


- Pandas `DataFrame` -> NumPy `array` to PyTorch `tensor` 

In [9]:
# Read the data from the csv file into a DataFrame
df = pd.read_csv(r"D:\WorkSpace\Machine Learning\PyTorch-for-Deep-Learning\C1-PyTorch Fundamentals\Module1\LAB3\data.csv")

# Extract the data as a NumPy array from the DataFrame
numpy_array_df = df.values

# Convert DataFrame's value to a PyTorch tensor
df_to_tensor = torch.from_numpy(numpy_array_df)
print(f"Shape of the tensor: {df_to_tensor.shape}")
print(f"Tensor datatype: {df_to_tensor.dtype}")

Shape of the tensor: torch.Size([3, 2])
Tensor datatype: torch.float64


- `torch.zeros()`

In [12]:
zeros = torch.zeros(3, 2)
print(f"Tensor with zeros: \n\n{zeros}")

Tensor with zeros: 

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


- `torch.ones()`

In [14]:
ones = torch.ones(2,3)
print(f"Tensor with ones: \n\n{ones}")

Tensor with ones: 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


- `torch.rand()`

In [17]:
random = torch.rand(2, 3)
print(f"Random tensor: \n\n{random}")

Random tensor: 

tensor([[0.9134, 0.1658, 0.3880],
        [0.7923, 0.6687, 0.6310]])


- `torch.randint(low, high, size())`

In [33]:
random_integer = torch.randint(9, 17, size=(3, 2))
print(f"Random integer: \n\n{random_integer}")

Random integer: 

tensor([[11, 16],
        [14, 16],
        [ 9, 10]])


- `torch.zeros_like()`, `torch.ones_like()`

In [20]:
zeros_like = torch.zeros_like(random)
ones_like = torch.ones_like(random)

print(f"Zeros like tensor: \n\n{zeros_like}\n")
print(f"Ones like tensor: \n\n{ones_like}")

Zeros like tensor: 

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones like tensor: 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


- `torch.arange()`

In [22]:
range_tensor = torch.arange(0, 10, step=1)
print(f"Range tensor: {range_tensor}")

Range tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


- Scaler, Vector, Matrix, Tensor

In [27]:
s = torch.tensor(10)
v = torch.tensor([7, 2, 9, 0])
M = torch.rand(2,3)
T = torch.rand(2, 3, 3)
print(f"Scaler: {s}")
print(f"="*50)
print(f"Vector: {v}")
print(f"="*50)
print(f"MATRIX: \n\n{M}")
print(f"="*50)
print(f"TENSOR: \n\n{T}")

Scaler: 10
Vector: tensor([7, 2, 9, 0])
MATRIX: 

tensor([[0.7529, 0.1189, 0.7403],
        [0.3049, 0.9010, 0.8888]])
TENSOR: 

tensor([[[0.3359, 0.2888, 0.4201],
         [0.9250, 0.0819, 0.3881],
         [0.4701, 0.9422, 0.5361]],

        [[1.0000, 0.1701, 0.3209],
         [0.9031, 0.4952, 0.9806],
         [0.9708, 0.5334, 0.3553]]])


-------

- `tensor.argmax()`, `tensor.max()`



* **dim=0** → across rows (down columns)
* **dim=1** → across columns (across a row)
* **dim=2** → across **depth / channels** (the 3rd axis)

---

**Rule:**
`dim = axis number` in a multi-dim tensor.

Example shape `(N, C, H, W)`:

* dim=0 → batch
* dim=1 → channels
* dim=2 → height
* dim=3 → width


In [61]:
v = torch.randint(5, 17, size=(5,))
print(f"Tensor shape: {v.shape}")
s, _ = v.max(dim=0)
print(f"Tensor v: {v}")
print(f"Maximum value: {s}")

Tensor shape: torch.Size([5])
Tensor v: tensor([12,  7, 16, 11, 12])
Maximum value: 16


In [60]:
V = torch.tensor([[10, 17, 11],
                  [19, 6, 21],
                  [12, 29, 10]])
print(f"Tensor shape: {v.shape}")
m, _ = V.max(dim=0) # Finds max across each column
print(f"Tensor v: \n{V}")
print(f"Maximum across each column: {m}")

Tensor shape: torch.Size([3, 3])
Tensor v: 
tensor([[10, 17, 11],
        [19,  6, 21],
        [12, 29, 10]])
Maximum across each column: tensor([19, 29, 21])


In [59]:
V = torch.tensor([[10, 17, 11],
                  [19, 6, 21],
                  [12, 29, 10]])
print(f"Tensor shape: {v.shape}")
m, _ = V.max(dim=1) # Finds max across each row
print(f"Tensor v: \n{V}")
print(f"Maximum across each row: {m}")

Tensor shape: torch.Size([3, 3])
Tensor v: 
tensor([[10, 17, 11],
        [19,  6, 21],
        [12, 29, 10]])
Maximum across each row: tensor([17, 21, 29])


In [65]:
torch.manual_seed(42)
X = torch.randint(0, 99, size=(3, 2, 2))
max_val, _ = X.max(dim=2)
print(X)
print(max_val)

tensor([[[ 6, 95],
         [97, 58]],

        [[90, 65],
         [25, 77]],

        [[85,  2],
         [67, 76]]])
tensor([[95, 97],
        [90, 77],
        [85, 76]])


**Reshaping & Manipulating:**

- `tensor.shape`, `tensor.ndim`, `tensor.dtype`

In [25]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"x tensor shape: {x.shape}")
print(f"x tensor dimension: {x.ndim}")
print(f"x tensor dimension: {x.dtype}")
print(f"Type of the object: {type(x)}")

x tensor shape: torch.Size([2, 3])
x tensor dimension: 2
x tensor dimension: torch.int64
Type of the object: <class 'torch.Tensor'>


- `torch.Tensor.unsqueeze()`

In [66]:
# Add extra dimension
TENSOR = torch.randint(0, 99, size=(2,3))
EXPANDED = TENSOR.unsqueeze(0)
print(f"Shape before adding dimension: {TENSOR.shape}")
print(f"Shape after adding dimension : {EXPANDED.shape}")

Shape before adding dimension: torch.Size([2, 3])
Shape after adding dimension : torch.Size([1, 2, 3])


- `torch.Tensor.squeeze()`

In [67]:
# Removing extra dimension
SQUEEZED = EXPANDED.squeeze()
print(f"Shape before removing dimension: {EXPANDED.shape}")
print(f"Shape after removing dimension : {SQUEEZED.shape}")

Shape before removing dimension: torch.Size([1, 2, 3])
Shape after removing dimension : torch.Size([2, 3])


- `torch.Tensor.reshape()`

In [69]:
T = torch.rand(3, 4)
T_RESHAPED = T.reshape(-1,12)
T_RESHAPED2 = T.reshape(3, 2, 2)
print(f"Shape of T_RESHAPED: {T_RESHAPED.shape}")
print(f"Shape of T_RESHAPED2: {T_RESHAPED2.shape}")

Shape of T_RESHAPED: torch.Size([1, 12])
Shape of T_RESHAPED2: torch.Size([3, 2, 2])


- `torch.Tensor.transpose()`

In [74]:
M = torch.rand(3, 4)
print(f"Shape of M: {M.shape}")
print(f"TENSOR M: \n\n{M}")
print("="*50)
M_TRANSPOSED = M.transpose(0, 1)
print(f"Shape of M: {M.shape}")
print(f"TENSOR M_TRANSPOSED: \n\n{M_TRANSPOSED}")

Shape of M: torch.Size([3, 4])
TENSOR M: 

tensor([[0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813],
        [0.7860, 0.1115, 0.2477, 0.6524]])
Shape of M: torch.Size([3, 4])
TENSOR M_TRANSPOSED: 

tensor([[0.6790, 0.7653, 0.7860],
        [0.9155, 0.2979, 0.1115],
        [0.2418, 0.8035, 0.2477],
        [0.1591, 0.3813, 0.6524]])


- `torch.cat()`